In [1]:
import numpy as np
array=[2,3,4,5,6]
type(array)

list

# Creating 1D Array

In [9]:
arr=np.array([2,4,5,6,7])
arr

array([2, 4, 5, 6, 7])

In [10]:
type(arr)

numpy.ndarray

# Creating a 2D Array


In [11]:
arr_2d=np.array([ [1,2,3] , [4,5,6] , [3,9,2] ])
arr_2d


array([[1, 2, 3],
       [4, 5, 6],
       [3, 9, 2]])

In [12]:
arr_2d.shape   

(3, 3)

In [13]:
arr.shape

(5,)

# Creating an array of zeroes

In [32]:
arrz=np.zeros([2,3])
#type(arrz) -> numpy.ndarray
#arrz.dtype->dtype('float64')
arrz=arrz.astype(int)
arrz


array([[0, 0, 0],
       [0, 0, 0]])

# Creating an array of ones

In [38]:
arr_ones=np.ones([3,3] , dtype=int)
#arr_ones=arr_ones.astype(int)
arr_ones


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# Creating an Array with a Specific Value

In [39]:
filler_arr=np.full((2,4) , 67)
filler_arr

array([[67, 67, 67, 67],
       [67, 67, 67, 67]])

# Sequence of numbers

In [42]:
seq_array=np.arange(0,100,20)  #100 is excluded like for loops in python
seq_array

array([ 0, 20, 40, 60, 80])

# line Space in Array

In [45]:
line_arr=np.linspace(1,100,5)  # 100 is included here by default.
line_arr

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

# Generating Random Arrays

In [46]:
rand_array=np.random.rand(2,3)  #[0,1)
rand_array

array([[0.62666707, 0.69624301, 0.42864062],
       [0.24369276, 0.78396053, 0.13615704]])

In [48]:
rand_array2=np.random.randint(55 , 100 , (3,4) )
rand_array2

array([[94, 68, 60, 89],
       [69, 99, 56, 99],
       [74, 65, 94, 88]], dtype=int32)

In [ ]:
#Function	                     Start	     End
''' np.arange(0,100,20)      	Included	Excluded
    np.random.randint(55,100)	Included	Excluded
    np.linspace(10,100,6)	    Included	Included ''' 