In [11]:
import numpy as np

# Indexing in a 2D Array

In [12]:
a1 = np.array([[10,20,30], [21,31,41]])
a1[1,2]

np.int64(41)

In [13]:
a1[0,1]

np.int64(20)

In [14]:
a1[0][1]

np.int64(20)

# Getting a row

In [15]:
a1[0]


array([10, 20, 30])

In [16]:
a1[0 ,:] 

array([10, 20, 30])

# Getting a column

In [17]:
a1[: , 0]

array([10, 21])

In [18]:
a1[: , 1]

array([20, 31])

# Array Splitting

In [19]:
a2=np.array([4,0,6,3,8,1])
a2.size

6

In [20]:
y=np.split(a2 , 3)
y

[array([4, 0]), array([6, 3]), array([8, 1])]

In [21]:
np.split(a2 , 6)

[array([4]), array([0]), array([6]), array([3]), array([8]), array([1])]

In [22]:
a2

array([4, 0, 6, 3, 8, 1])

# Math operations on Arrays

In [25]:
a3=([1,2,3,4,5])
a4=np.square(a3)
a4

array([ 1,  4,  9, 16, 25])

In [26]:
np.square(a3)

array([ 1,  4,  9, 16, 25])

In [27]:
a3

[1, 2, 3, 4, 5]

# Aggregate functions

In [28]:
a5=np.array([4,5,2,9,8])
a5

array([4, 5, 2, 9, 8])

In [38]:
s=np.sum(a5)
s


np.int64(28)

In [30]:
k=np.prod(a5)
k

np.int64(2880)

In [31]:
np.mean(a5)

np.float64(5.6)

In [32]:
np.max(a5)

np.int64(9)

In [33]:
np.median(a5)

np.float64(5.0)

In [36]:
a5

array([4, 5, 2, 9, 8])

In [37]:
std_dev=np.std(a5)
std_dev

np.float64(2.5768197453450252)

# Array Sorting in Numpy

In [39]:
a6=np.array([15,61,2,89,56,230])
a6
            

array([ 15,  61,   2,  89,  56, 230])

In [44]:
np.sort(a6)


array([  2,  15,  56,  61,  89, 230])

In [45]:
a6

array([ 15,  61,   2,  89,  56, 230])

# Array Searching

In [46]:
a6

array([ 15,  61,   2,  89,  56, 230])

In [47]:
key=np.where(a6==61)
key

(array([1]),)

In [48]:
key2=np.where(a6==230)
key2

(array([5]),)