In [1]:
import numpy as np

# NumPy Array Operations

In [76]:
arr1=np.arange(1,10,2) 
arr1

array([1, 3, 5, 7, 9])

In [9]:
arr2=np.arange(10,20,2)
arr2

array([10, 12, 14, 16, 18])

In [92]:
sum=arr1+arr2
sum


array([11, 15, 19, 23, 27])

# Indexing in 1D Array

In [57]:
arr3=np.arange(3,19)
arr3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [14]:
arr3[0]

np.int64(3)

In [15]:
arr3[1]

np.int64(4)

In [16]:
arr3[-1]

np.int64(18)

In [18]:
arr3[1:4] #like loops for i in range(start , end) end is not included.

array([4, 5, 6])

In [19]:
arr3[4:6]

array([7, 8])

In [23]:
arr3[0:16:2]

array([ 3,  5,  7,  9, 11, 13, 15, 17])

In [27]:
arr3[5:1:-1]

array([8, 7, 6, 5])

In [29]:
arr3[-1:-1:-1]

array([], dtype=int64)

In [52]:
arr3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [53]:
arr3[::-1]

array([18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3])

In [54]:
arr3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [58]:
arr3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [59]:
arr3>12

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True])

In [61]:
arr3[arr3>=12]

array([12, 13, 14, 15, 16, 17, 18])

# Reshaping Array

In [63]:
arr4=np.arange(11,30,2)
arr4

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [64]:
len(arr4)

10

In [65]:
arr4.size

10

In [66]:
arr4.shape

(10,)

In [67]:
arr5=np.array([ [2,3,4] , [5,6,7] ])
len(arr5)

2

In [68]:
arr5.shape

(2, 3)

In [69]:
arr5.size

6

In [71]:
arr4.reshape(5,2)  #Reshaping.

array([[11, 13],
       [15, 17],
       [19, 21],
       [23, 25],
       [27, 29]])

In [73]:
arr4.reshape(-1,1) #transpose.

array([[11],
       [13],
       [15],
       [17],
       [19],
       [21],
       [23],
       [25],
       [27],
       [29]])

# Flattended Array

In [84]:
arr6 = np.array(
    [[2,3,8],[9,5,1],[4,1,9]]
)
arr6

array([[2, 3, 8],
       [9, 5, 1],
       [4, 1, 9]])

In [80]:
arr6.ravel()

array([2, 3, 8, 9, 5, 1, 4, 1, 9])

In [81]:
arr6

array([[2, 3, 8],
       [9, 5, 1],
       [4, 1, 9]])

# Stack Joined Array

In [82]:
arr7=([67,1,89]) 
arr8=([69,78,84])

harr=np.hstack((arr7 , arr8))
harr

array([67,  1, 89, 69, 78, 84])

In [83]:
varr=np.vstack((arr7 , arr8))
varr


array([[67,  1, 89],
       [69, 78, 84]])